name = "bokksu-backend"
type = "webpack"

account_id = "d821c1c5e1a8582b220e39739ae92aa9"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [ 
  { binding = "DATA", id = "03d32307823b449798c86fc7af630b96" }
]
