export default [
  {
    id: 1,
    model: '01-pizza.fbx',
    name: 'Pizza',
    nameEn: 'Pizza',
    template: '01-pizza.png',
    download: '01-pizza.png',
    objectName: 'pizza_congelada_1',
    planeName: 'Plane_pizza_congelada_1',
    separation: 4,
    cameraData: [0, 0, 0, 0, 6, 6],
  },
  {
    id: 2,
    model: 'envase_galletitas.fbx',
    name: 'Galletitas dulces',
    nameEn: 'Sweet cookies',
    template: 'envase_galletitas.png',
    download: 'envase_galletitas.png',
    objectName: 'Galletitas_1',
    planeName: 'PlaneGalletitas_1',
    separation: 3,
    cameraData: [0, 1, 0, 1.773 * 2, 1.2 * 2, 1.99 * 2],
  },
  {
    id: 3,
    model: 'envase_leche-saborizada.fbx',
    name: 'Leche Saborizada',
    nameEn: 'Flavored milk',
    template: 'envase_leche-saborizada.png',
    download: 'envase_leche-saborizada.psd',
    objectName: 'Estuche_leche_1',
    planeName: 'Plane_leche',
    separation: 1.5,
    cameraData: [0, 1, 0, 1.773 * 2, 1.2 * 2, 1.99 * 2],
  },
  {
    id: 4,
    model: 'envase_granola.fbx',
    name: 'Granola',
    nameEn: 'Granola',
    template: 'envase_granola.png',
    download: 'envase_granola.png',
    objectName: 'Granola',
    planeName: 'PlaneGranola_1',
    separation: 2.5,
    cameraData: [0, 1, 0, 1.773 * 2, 1.2 * 2, 1.99 * 2],
  },
  {
    id: 5,
    model: '04-chocolate.fbx',
    name: 'Chocolate',
    nameEn: 'Chocolate',
    template: '04-chocolate.png',
    download: '04-chocolate.png',
    objectName: '04_obj_chocolate',
    planeName: '04_plane_chocolate',
    separation: 2.5,
    cameraData: [0, 0.7, 0, 2.1276, 2.4, 4.577],
  },
];
